<?php
/**
 * Created by PhpStorm.
 * User: cy
 * Date: 2019/12/26
 * Time: 10:46
 */

namespace app\index\v1;


use think\Controller;
use think\Request;
use think\facade\Request as fRequest;

class Duo extends Controller
{
    public $beforeActionList = [
        'before' => ['only' => 'test']  // 为啥没执行
    ];

    public function before()
    {
        echo 'before';
    }

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        echo '1111';
    }

    public function test1($id, $name)
    {
        var_dump(223455);
        var_dump($id, $name);
    }

    public function test(Request $request)
    {
        return json(['name' => 'cy'], 200, ['xixi' => 'cy']);

        var_dump(111,fRequest::ext());exit;

        var_dump(fRequest::put('name'));exit;

        var_dump($this->request->method(true));exit;
        //var_dump($_SERVER["HTTP_REFERER"]);exit;
       //return ['name' => 'cy'];
    }
}